#ifndef GAIA_CHUNK_CONSTANTS_H
#define GAIA_CHUNK_CONSTANTS_H

constexpr int CHUNK_SIZE = 16;
constexpr int CHUNK_AREA = CHUNK_SIZE * CHUNK_SIZE;
constexpr int CHUNK_VOLUME = CHUNK_SIZE * CHUNK_SIZE * CHUNK_SIZE;

#endif